### ISSUE TITLE
Add commands for CMD and Powershell

### ISSUE THREAD

**Issue by prithaupadhyay** [aashutoshrathi/HackerRank-Test-Case-Generator#65]
Screenshot of the issue:

![image](https://user-images.githubusercontent.com/21213021/54685468-e6929d80-4b3c-11e9-8fbe-213af79a66a1.png)

**Comment by aashutoshrathi** [comment]
### Brief description of the issue

The project contains a file named `lang_compiler.py` which contains all commands that should be executed. But since the application was initially developed on Linux, to execute binary files generated by C/C++, I called `./logic` instead on windows like terminals, we have to call `logic` since `.` is not anything on CMD or PS environment.
You have to check OS and accordingly execute the command and this can be easily done with changing few lines hence added this as a begineer issue.

**Comment by helios1101** [comment]
Can i work on this fix??

**Comment by aashutoshrathi** [comment]
Yeah sure @helios1101

**Comment by Sagar2366** [comment]
https://github.com/aashutoshrathi/HackerRank-Test-Case-Generator/pull/83
